[tool.ruff]
line-length = 88
respect-gitignore = true
target-version = "py311"

[tool.ruff.lint]
select = ["E", "F", "I", "N", "B"]
ignore = ["B008"]
exclude = ["migrations", "__pycache__"]

[tool.ruff.format]
docstring-code-format = true
quote-style = "preserve"
line-ending = "lf"
