name: Deploy to DigitalOcean

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DO_SSH_KEY }}

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DO_SSH_USERNAME }}@${{ secrets.DO_HOST }} << 'EOF'
            set -e
            cd ~/trading-exchange-sim
            git pull origin main
            docker-compose down
            docker-compose up -d --build
          EOF
